src/queue-list/laboratory-queue.component.tsx
=> fix : rename list component

yarn.lock
=> fix: lock file

src/patient-chart/laboratory-order.component.tsx, src/patient-chart/results-summary/test-results-table.component.tsx
- fix key arrangements
- remove unnecessary empty message
=> fix : key arrangements

src/patient-chart/results-summary/print-results-table.component.tsx
- add units and reference range on print preview
- below is screenshot attached
=> ft : add reference range , units in print preview

src/completed-list/completed-list.component.tsx, src/review-list/review-list.component.tsx, src/work-list/work-list.component.tsx
- fix table lists pagination
https://github.com/METS-Programme/openmrs-esm-laboratory/assets/24471994/bf5385f0-4ca2-431d-8a90-d1a0aece94f4
=> (fix) : fix table lists paginations

src/completed-list/completed-list.component.tsx, src/queue-list/laboratory-patient-list.component.tsx, src/review-list/review-list.component.tsx, src/work-list/work-list.component.tsx
- remove filtering by ascending order for tables
=> fix: remove ascending and descending ordering

src/queue-list/laboratory-patient-list.component.tsx
- remove order type from tests ordered table
-
=> ff : remove order type from test ordered table

README.md
=> Update README.md screenshots url

src/queue-list/laboratory-patient-list.component.tsx, src/queue-list/laboratory-patient-list.resource.ts, src/work-list/work-list.component.tsx
=> A minor issue related to spelling.

src/results/result-form-field.component.tsx, src/results/result-form.component.tsx, src/work-list/work-list.component.tsx
Bug fix on handling results for concepts with no set members
=> (fix) handle saving of lab result for concepts with no set members

src/summary-tiles/summary-tile.component.tsx
This Pr Adds a space between Button view and Arrow Right
Pr https://openmrs.atlassian.net/browse/O3-2726
Before
After
cc @pirupius @jabahum
=> Add space between button view and ArrowRight

package.json, src/patient-chart/laboratory-order.component.tsx, src/routes.json
https://metsprogramme.atlassian.net/browse/U4X-356
=> Arrange lab results on patient summary in descending order

src/patient-chart/laboratory-order.component.tsx
https://metsprogramme.atlassian.net/browse/U4X-377
=> Fixing pagination of lab results on patient chart and table toolbar search functionality

src/completed-list/completed-list.component.tsx, src/completed-list/completed-list.scss, src/lab-tabs/approved-tab.component.tsx, src/lab-tabs/referred-tab.component.tsx, src/lab-tabs/review-tab.component.tsx, src/lab-tabs/work-list-tab.component.tsx, src/patient-chart/laboratory-order.scss, src/patient-chart/results-summary/print-results-summary.scss, src/patient-chart/results-summary/results-summary.scss, src/queue-list/lab-tests/lab-tests.component.tsx, src/queue-list/laboratory-patient-list.component.tsx, src/queue-list/laboratory-queue.scss, src/queue-list/laboratory-tabs.component.tsx, src/review-list/review-list.component.tsx, src/review-list/review-list.scss, src/work-list/work-list.component.tsx, src/work-list/work-list.scss
There have been some residue from the tabs refactor that left in blank divs. These added unnecessary white spaces within the UI
Before
After
=> (fix) remove blank div from lab tabs

src/review-list/dialog/review-item.component.tsx
This PR fixes a bug when making and approval
=> (fix) : Fix approval bug.

package.json, src/patient-chart/results-summary/results-summary.scss, src/patient-chart/results-summary/test-results-table.component.tsx
=> Removing the actions column in the expanded row of test-results-summary

src/patient-chart/laboratory-active-test-order/laboratory-active-test-order-results.component.tsx, src/patient-chart/laboratory-order-referals/laboratory-order-referals.component.tsx, src/patient-chart/laboratory-past-test/laboratory-past-test-order-results.component.tsx, src/patient-chart/results-summary/test-print-results-table.component.tsx, src/patient-chart/results-summary/test-results-table.component.tsx
This PR removes  encounters without encounterType Lab
=> (fix) : filter by lab encounter type and remove unnecessary encounter entries

src/index.ts, src/lab-tabs/rejected-tab.component.tsx, src/lab-tiles/rejected-tile.component.tsx, src/reject-order/rejected-tests-list.component.tsx, src/routes.json, src/summary-tiles/laboratory-summary-tiles.scss, src/tests-ordered/tests-ordered-list.component.tsx
=> Handle Rejected Tests

src/lab-tiles/completed-tile.component.tsx, src/review-list/dialog/review-item.component.tsx, src/review-list/dialog/review-item.scss, src/review-list/review-list.component.tsx, src/routes.json, src/summary-tiles/laboratory-summary.resource.tsx
Fix approval of resulted tests
=> Fix Approval of Resulted Tests

src/laboratory-resource.ts
To solve 400 error when the pick up lab request api is called.
https://openmrs.atlassian.net/browse/O3-3201
=> (fix) O3-3201 Fix 400 error

src/components/orders-table/orders-data-table.component.tsx, src/config-schema.ts
Clicking on a patient name on the Lab App for Tests Ordered and In Progress should deep link  to the patient chart Orders widget
https://openmrs.atlassian.net/browse/O3-3203
=> (feat) O3-3203 Deeplink Lab App Orders to Patient Chart Orders

src/index.ts, src/lab-tabs/laboratory-tabs.component.tsx, src/lab-tiles/laboratory-summary-tiles.component.tsx, yarn.lock
Updates `ComponentContext` to include `featureName`
=> (fix) Adds missing featureName from ComponentContext

yarn.lock
This PR bumps openmrs core and framework.
=> (chore): Bump core

package.json
This PR cuts a patch release. Draft changelog:
* (fix) Orders data table UI fixes by @denniskigen in https://github.com/openmrs/openmrs-esm-laboratory-app/pull/118
* (chore) Update translations from Transifex by @github-actions in https://github.com/openmrs/openmrs-esm-laboratory-app/pull/116
=> (chore): Release v1.0.1

README.md, package.json
Cuts a patch release of the Laboratory App, v1.0.2 with a bug fix for invalid dates in the Orders date range picker and translation updates from Transifex.
This diff also includes an unrelated change fixing a syntax issue in the README.md file.
=> (chore) Release v1.0.2

src/index.ts, translations/en.json
This PR adds the missing translation string for the `Declined test` tab.
=> (fix): Add missing translations for declined tests tab

src/index.ts, translations/en.json
This PR updates the translation key to match the casing of the actual text.
=> (fix): Update casing in translation string
