i18next-parser.config.js
package.json
src/config-schema.ts
src/patient-chart/laboratory-item/view-laboratory-item.component.tsx
src/patient-chart/laboratory-item/view-laboratory-item.resource.ts
src/patient-chart/laboratory-order.component.tsx
src/patient-chart/laboratory-order.resource.ts
src/patient-chart/results-summary/results-summary.component.tsx
src/patient-chart/results-summary/results-summary.resource.tsx
src/patient-chart/results-summary/results-summary.scss
src/patient-chart/results-summary/results/results.component.tsx
src/patient-chart/results-summary/results/results.resource.ts
src/patient-chart/results-summary/test-children-results.component.tsx
src/patient-chart/results-summary/test-print-results-table.component.tsx
src/patient-chart/results-summary/test-results-rescend-action-menu.component.tsx
src/patient-chart/results-summary/test-results-table.component.tsx
src/patient-chart/results-summary/tests-children-detail.component.tsx
webpack.config.js

ft : order status color

---

src/queue-list/lab-tests/lab-tests.component.tsx
src/queue-list/laboratory-patient-list.component.tsx
src/queue-list/pick-lab-request-menu.component.tsx
src/review-list/dialog/review-item.component.tsx
src/review-list/dialog/review-item.resource.ts
src/summary-tiles/laboratory-summary-tiles.component.tsx
src/work-list/work-list.component.tsx

- decouple tests orders from queue
- screenshots
-

fix : decouple tests orders from patient queues

---

src/completed-list/completed-list.component.tsx
src/queue-list/laboratory-patient-list.component.tsx
src/review-list/review-list.component.tsx
src/work-list/work-list.component.tsx

- add patient on all orderslist tables
-

(feat) add patient name to laboratory dashboard

---

src/queue-list/lab-dialogs/add-to-worklist-dialog.component.tsx

A minor ui fix that removes a misplaced labelText when selecting an order's specimen type
Before: 
After:

Remove select labelText for a clean ui

---

src/completed-list/completed-list.component.tsx
src/completed-list/completed-list.scss
src/queue-list/laboratory-patient-list.component.tsx
src/queue-list/laboratory-queue.scss

I introduced CustomTableRow Component  which Promotes a cleaner and more modular structure by encapsulating the row rendering logic in a CustomTableRow  component. 
Also i did some  code refactory makes it easier to manage the changes in the structure of the table.
Though the initial approach also has an advantage in the way that it makes each table cell individually defined which makes customization little easy than this approach which is more generic. Let me know your suggestions.  cc @denniskigen  @pirupius @jabahum . Thanks.

Encapsulate  the row rendering logic in a separate component

---

src/results/result-form.component.tsx
src/results/result-form.resource.ts

…ssociated observation results
Bug fix for saving lab results. This fix also combines API calls for updating order status and the associated observations
NOTE: There is a need to improve the function that merges the API for better chaining and error handling

(fix) add a function that combines calls to update an order and the associated observation results

---

src/index.ts
src/order-actions/reject-order.component.tsx
src/queue-list/laboratory-patient-list.component.tsx
src/queue-list/pick-lab-request-menu.component.tsx
src/routes.json
src/ui-components/overflow-menu.component.tsx
src/ui-components/overflow-menu.scss
translations/en.json

This PR is addressing the issue of adding adding an extension slot under lab order actions to make this more configurable so that implementations can add in whatever custom order actions that suit their needs

(feat) lab order actions  - Add order-actions-slot and switches icons for overflow menu 

---

src/results/result-form-field.component.tsx
src/results/result-form.component.tsx
src/results/result-form.scss

Mark all fields in the lab result form as required and prevent submission of form
Single concept: ![image](https://github.com/openmrs/openmrs-esm-laboratory/assets/2161877/9c634e0d-b83d-4a8f-b088-dbdd62aef925)
Concept for panel: ![image](https://github.com/openmrs/openmrs-esm-laboratory/assets/2161877/d7f44590-84d5-48fe-97f0-d30fe7d0944c)

mark fields in the lab result form as required

---

README.md
src/queue-list/laboratory-tabs.component.tsx
yarn.lock

…
The PR is addressing the issue of the lab-panels-slot which will not be visible in the implementer tools UI when used below
in the value for `ComponentContext.Provider` as the UI viewer depends on the div that cannot be added because of how the Carbon components work. Implementers can add more tab extensions to this slot via the routes.js file configuration.

revise-panels:refining the rendering of extensions in the lab-panels-slot

---

src/config-schema.ts
src/queue-list/lab-dialogs/add-to-worklist-dialog.component.tsx
src/queue-list/lab-dialogs/add-to-worklist-dialog.resource.ts

https://github.com/openmrs/openmrs-esm-laboratory/assets/24471994/b38db9a8-7deb-4674-8339-38ff41cecf2e
https://metsprogramme.atlassian.net/browse/U4X-358

U4X-358 : Barcode and referal / shipping inclusion 

---

README.md
src/index.ts
src/lab-tiles/completed-tile.component.tsx
src/lab-tiles/referred-tile.component.tsx
src/lab-tiles/tests-ordered-tile.component.tsx
src/lab-tiles/worklist-tile.component.tsx
src/routes.json
src/summary-tiles/laboratory-summary-tiles.component.tsx
src/summary-tiles/laboratory-summary-tiles.scss

The PR is also addressing the similar  issue of the lab-tiles-slot which will not be visible in the implementer tools UI when used below
in the value for ComponentContext.Provider as the UI viewer depends on the div that cannot be added because of how the Carbon components work. Implementers can add more tab extensions to this slot via the routes.js file configuration.

tile:adding summary tiles as extesnions

---

src/queue-list/laboratory-patient-list.component.tsx
translations/en.json

This PR addresses the issue of filtering orders by status in the Tests ordered tab 
https://www.loom.com/share/0a7d15e5f8384314b931aedb55c6d6c6?sid=7af4fda7-161f-4915-b03e-e7a94b93cf8b

status:Filter lab orders by status

---

package.json
src/patient-chart/laboratory-active-test-order/laboratory-active-test-order-results.component.tsx
src/patient-chart/laboratory-order-referals/laboratory-order-referals.component.tsx
src/patient-chart/laboratory-past-test/laboratory-past-test-order-results.component.tsx
src/patient-chart/patient-laboratory-results.component.tsx

https://github.com/openmrs/openmrs-esm-laboratory/assets/89844768/c01dc8d5-ba47-4eac-93f8-677263c8de4f

Fixing pagination for Active Tests and Past Order Results Data Tables under routine tests tab on patient chart

---

src/config-schema.ts
src/queue-list/lab-dialogs/add-to-worklist-dialog.component.tsx
src/queue-list/lab-dialogs/add-to-worklist-dialog.resource.ts
yarn.lock

This PR introduces logic to make specimen id generation configurable. If the flag is not enabled, users should be allowed to enter the specimen id and the specimen id generation button should be hidden. If the flag is enabled on the other hand, the text field should be readonly and the auto generation button displayed.
https://github.com/openmrs/openmrs-esm-laboratory/assets/12844964/49e21573-d87d-4c05-8483-4ec3a1571a83

(feat) Make Specimen Id generation configurable

---

src/config-schema.ts
src/work-list/work-list.resource.ts

Display orders for tests only

---

package.json
src/components/orders-table/orders-data-table.component.tsx
src/components/orders-table/orders-data-table.scss
src/constants.ts
src/lab-tabs/modals/pickup-lab-request-modal.component.tsx
src/laboratory-resource.ts
yarn.lock

Update how we show default lab orders to default to current date orders. In addition include ability to filter by selected on or after date for the lab orders.
https://openmrs.atlassian.net/browse/O3-3366

(feat) O3-3366: Add ability to filter lab order by `activatedOnOrAfterDate` params

---

src/lab-tabs/data-table-extensions/completed-lab-requests-table.extension.tsx
src/results/result-form.component.tsx

This PR adds ability to transition order and mark it as completed once test result form has entered the results.
In addition i have also removed the `action` column on the completed lab tab
https://github.com/openmrs/openmrs-esm-laboratory-app/assets/28008754/99c79421-9c02-4e84-a1dc-ec1a7fded5f6

(feat) O3-3373: Add ability to mark fulfiller status as completed when saving test results

---

src/components/orders-table/orders-data-table.component.tsx
translations/am.json
translations/en.json
translations/es.json
translations/fr.json
translations/he.json
translations/km.json

Renames the `Action` column to `Modification`
https://openmrs.atlassian.net/browse/O3-3202

(fix) [O3-3202] Rename `Action` column to `Modification`

---

tsconfig.json

Based on the comment on this PR https://github.com/openmrs/openmrs-esm-core/pull/1085. I updated the `tsconfig` to include "es2022" as a valid option to solve  Object.hasOwn() error.
**Before upgrading the tsconfig file**
**After updating the tsconfig file**

(fix) Update tsconfig to include "es2022"

---

src/config-schema.ts
src/results/result-form.component.tsx
src/results/result-form.resource.ts

This PR modifies the `obs` payload which modified an existing encounter, to now send data to the encounter endpoint as a new encounter with the `obsDatetime` property added to each observation.
https://openmrs.atlassian.net/browse/O3-3571

(O3-3571): Modify results observation payload to send data as an encounter. 

---

src/lab-tiles/laboratory-summary-tiles.scss

The cardContainer on the Home page of the lab app has been updated to resolve the issue of excessive space on the right-hand side after verifying that the cardContainer was only rendering 3 cards instead of the anticipated 5, which caused the layout to have redundant space on the right.
**Before fixing the changes** 
https://github.com/user-attachments/assets/f537ee00-d7f5-44d9-816b-ee61dab5c28e
**After fixing the proposed changes**
https://github.com/user-attachments/assets/940dc262-4e4a-4c23-b173-63c7379e7316
https://openmrs.atlassian.net/browse/O3-3795

(fix) O3-3795: Adjust tile spacing in lab dashboard

---

src/components/orders-table/orders-data-table.component.tsx
src/components/orders-table/orders-data-table.scss
src/components/orders-table/orders-date-range-picker.scss
src/components/orders-table/orders-date-range-picker.tsx
src/lab-tabs/data-table-extensions/completed-lab-requests-table.extension.tsx
src/lab-tabs/data-table-extensions/in-progress-lab-requests-table.extension.tsx
src/laboratory-resource.ts
src/types.ts

In this PR I have added a date range picker to allow for fetching of data by date ranges. As highlighted by @donaldkibet [here](https://openmrs.atlassian.net/browse/O3-3916) it makes it easier to track and follow up on ordered test results.
While I was at it I refactored the loading state a little bit to make the UI consistent between loading and loaded states. to reduce the amount of 'layout shift' that happens.
https://openmrs.atlassian.net/browse/O3-3916

fix: replaced single date picker for date range picker in the lab results component.

---

.github/workflows/tx-pull.yml
.github/workflows/tx-push.yml
.tx/config

Ticket: https://openmrs.atlassian.net/browse/O3-4041

O3-4041: Add transifex translations

---

package.json
src/components/orders-table/list-order-details.component.tsx
yarn.lock

This PR bumps the `@openmrs/esm-framework`, `openmrs` tooling and `@openmrs/esm-patient-common-lib`.
None
None

(chore) Bump framework and core tooling

---

src/lab-tabs/modals/pickup-lab-request-modal.component.tsx
src/lab-tabs/modals/pickup-lab-request-modal.scss
src/lab-tabs/modals/reject-lab-request-modal.component.tsx
src/lab-tabs/modals/reject-lab-request-modal.scss

while clicking the pick lab request in the laboratory  app and reject lab request 
modal pop for that close icon is not aligned correctly 
[close modal css is not aligned correctly ]
x

(fix) O3 4341: Fix modal close buttons placement in the lab app

---

src/components/orders-table/list-order-details.component.tsx
src/components/orders-table/list-order-details.scss
src/components/orders-table/orders-data-table.component.tsx

This PR makes the following changes to the Orders data table:
- Conditionally applying the zebra striping to the table rows based on the number of orders.
- Removing an unnecessary top border from the name order row.

(fix) Orders data table UI fixes

---

src/lab-tabs/actions/add-lab-request-results-action.component.tsx
src/laboratory-resource.ts

This PR fixes an issue whereby the lab order would not automatically be transitioned to the complete status whenever a user finishes adding lab results.
https://github.com/user-attachments/assets/883336ff-0c23-4d3b-b194-74098a18312e
https://openmrs.atlassian.net/browse/O3-4398
This work is dependent on the work on the patient chart app that makes the workspace accept the `mutateLabOrders` prop that I pass on this PR. So ideally both of these PRs should be merged at the same time.
The PR on the patient chart orders app can be found [here.](https://github.com/openmrs/openmrs-esm-patient-chart/pull/2225)

(fix) O3-4398: Invalidate lab orders after submitting results form

---

src/components/orders-table/orders-date-range-picker.component.tsx
src/laboratory-dashboard.component.tsx

Fixes an issue where the date range picker in the laboratory dashboard was throwing an error because the default date format for the Carbon date picker is `m/d/Y` while the date range picker was providing dates in the format `d/m/Y`. Explicitly setting the date format to `d/m/Y` fixes the issue.
Other unrelated changes in the diff include:
- Removing the `omrs-main-content` class from the laboratory dashboard, as it doesn't do anything useful
- Reordering imports for easier reading
- Replacing the date range picker's `onClose` prop with an `onChange` prop, allowing date range changes to be reflected in the UI immediately

(fix) Fix invalid date error in laboratory dashboard

---

src/components/orders-table/orders-data-table.component.tsx

Uses patient person display instead of the generated patient display. The latter is a combination of the unique identifier and patient name with the identifier varying for different organizations. 
Using the `split('-')` when the identifier has a hyphen (-) breaks the logic 
For the example above, we end up with `25` which is part of the identifier instead of the patient name
After switching to person display

(fix) Use patient person display for patient name
